Completed Lesson1_2 homework
Dmitriy2077/TeachMeSkillsDmitriyHomework pull request #1
Opened 2021-10-11 13:03 UTC by Dmitriy2077

2021-10-16 20:02 UTC, nickrograch requested changes
8 задача решена неверно. Пример: "веревка" - твоя программа выдаёт, что первый повторяющийся символ - `в`, но первый повторяющийся - 'е'
![image](https://user-images.githubusercontent.com/48067169/137600795-13121305-ba2e-41de-a642-0950630b7b0f.png)

2021-10-16 20:02 UTC, nickrograch commented on src/lesson1_2/Lesson1_2Task1.java
> +        int numberForCheck = scanner.nextInt();
При названии переменных, если во фразе есть For или Of, то чаще всего их можно опустить.
В твоём случае вместо `numberForCheck` можно использовать `checkNumber`

2021-10-16 20:02 UTC, nickrograch commented on src/lesson1_2/Lesson1_2Task1.java
> +        int counterForNumberSize = 0;
Тут аналогично. `numberSizeCounter`

2021-10-16 20:02 UTC, nickrograch commented on src/lesson1_2/Lesson1_2Task1.java
> +        String typeOfNumber = "zero.";
Тут аналогично. `numberType`

2021-10-16 20:02 UTC, nickrograch commented on src/lesson1_2/Lesson1_2Task1.java
> +        int temporaryCopyOfNumber = numberForCheck;
Тут аналогично. `temporaryNumberCopy`

2021-10-16 20:02 UTC, nickrograch commented on src/lesson1_2/Lesson1_2Task4.java
> +
Удали лишнюю(ие) пустую(ые) строку(и)

2021-10-16 20:02 UTC, nickrograch commented on src/lesson1_2/Lesson1_2Task5.java
> +                negativeNumbers++;
Эта проверка не обязательна, достаточно проверить на `0`. 
`if (i != 0) negativeNumbers++`

2021-10-16 20:02 UTC, nickrograch commented on src/lesson1_2/Lesson1_2Task5.java
> +    }
Собственно этот метод не нужен.

2021-10-16 20:02 UTC, nickrograch commented on src/lesson1_2/Lesson1_2Task8.java
> +
Удали лишнюю(ие) пустую(ые) строку(и)

2021-10-19 11:54 UTC, Dmitriy2077 commented on src/lesson1_2/Lesson1_2Task1.java
> +        int numberForCheck = scanner.nextInt();
Исправлено.

2021-10-19 11:54 UTC, Dmitriy2077 commented on src/lesson1_2/Lesson1_2Task1.java
> +        int counterForNumberSize = 0;
Исправлено.

2021-10-19 11:54 UTC, Dmitriy2077 commented on src/lesson1_2/Lesson1_2Task1.java
> +        String typeOfNumber = "zero.";
Исправлено.

2021-10-19 11:54 UTC, Dmitriy2077 commented on src/lesson1_2/Lesson1_2Task1.java
> +        int temporaryCopyOfNumber = numberForCheck;
Исправлено.

2021-10-19 11:54 UTC, Dmitriy2077 commented on src/lesson1_2/Lesson1_2Task5.java
> +                negativeNumbers++;
Исправлено.

2021-10-19 11:54 UTC, Dmitriy2077 commented on src/lesson1_2/Lesson1_2Task5.java
> +    }
Исправлено.

2021-10-19 11:58 UTC, Dmitriy2077 commented on src/lesson1_2/Lesson1_2Task4.java
> +
@nickrograch А все ли пустые строки удалять надо или только в конце методов и классов?

2021-10-19 11:59 UTC, Dmitriy2077 commented on src/lesson1_2/Lesson1_2Task8.java
> +
Исправлено.

2021-10-28 09:17 UTC, nickrograch commented on src/lesson1_2/Lesson1_2Task4.java
> +
@Dmitriy2077 Ответил в ПР к комиту 3 урока

2021-10-28 09:19 UTC, nickrograch approved these changes

2021-10-28 09:21 UTC, nickrograch commented
@Dmitriy2077 не могу замержить. У тебя не все скриншоты в папке source\screenshots

2021-11-04 14:18 UTC, merged