Completed Lesson3 homework
Dmitriy2077/TeachMeSkillsDmitriyHomework pull request #2
Opened 2021-10-14 10:58 UTC by Dmitriy2077

2021-10-16 20:27 UTC, nickrograch requested changes
Ух, плотненько ты так зафигачил) но косякнул всё-таки.
Почему в этой ветке\коммите\пулл реквесте находятся файлы предыдущей задачи и README? убери их. в этой ветке должны быть файлы только относящиеся к задаче 3 урока

2021-10-16 20:27 UTC, nickrograch commented on src/lesson3/Lesson3_Task1.java
> +
Удали лишнюю(ие) пустую(ые) строку(и)

2021-10-19 13:17 UTC, Dmitriy2077 commented on src/lesson3/Lesson3_Task1.java
> +
@nickrograch А все ли пустые строки удалять надо или только в конце методов и классов?

2021-10-28 09:14 UTC, nickrograch commented on src/lesson3/Lesson3_Task1.java
> +
@Dmitriy2077 в конце. 
пустой строкой отделяются?:
> блок инициализации переменных, логика и строка возврата (если метод должен что-то возвращать)
Пример:
```
public int 2DigitSum(){
   int a = 1;
   int b = 2;
   int c;

   c = a + b;

   return c;
}
```

> Методы друг от друга:
```
public void method1(){
   ...
}

public void method2(){
   ...
}
```

2021-10-28 09:16 UTC, nickrograch approved these changes

2021-10-28 09:16 UTC, merged